version: "2"

services:
  web_crawler:
    build: .
    command: scrapy crawl web_crawler -a search_param=X -O tmp/data/active_listings_x.csv
    volumes:
      - .:/app
  er:
    build: .
    command: python3 entity_resolution/er.py tmp/data/active_listings_x.csv tmp/plot/active_listings_x.html
    volumes:
      - .:/app
  format:
    build: .
    command: poetry run black .
    volumes:
      - .:/app
