version: "2"

services:
  web_crawler:
    build: .
    command: poetry run er_pipeline run_crawler
    volumes:
      - .:/app
  er:
    build: .
    command: poetry run er_pipeline run_er
    volumes:
      - .:/app
  view_er:
    build: .
    ports:
      - "8000:8000"
  format:
    build: .
    command: poetry run black .
    volumes:
      - .:/app
