version: "2"

services:
  web_crawler:
    build:
      context: .
      target: builder
    command: poetry run er_pipeline run_crawler
    volumes:
      - .:/app
  er:
    build:
      context: .
      target: builder
    command: poetry run er_pipeline run_er
    volumes:
      - .:/app
  view_er:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  format:
    build:
      context: .
      target: builder
    command: poetry run black .
    volumes:
      - .:/app
